<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 3.1.2
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8"/>
    <title>Metronic | Admin Dashboard Template</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/font-awesome/css/font-awesome.min.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/simple-line-icons/simple-line-icons.min.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/bootstrap/css/bootstrap.min.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/uniform/css/uniform.default.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')  ?>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/select2/select2.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/admin/pages/css/login.css')  ?>
    <!-- END PAGE LEVEL SCRIPTS -->
    <!-- BEGIN THEME STYLES -->
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/css/components.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/css/plugins.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/admin/layout/css/layout.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/admin/layout/css/themes/default.css')  ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/admin/layout/css/custom.css')  ?>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- BEGIN BODY -->
<!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
<!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
<!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
<!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
<!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
<!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
<!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
<body class="login">
<!-- BEGIN LOGO -->
<div class="logo">
    <a href="index.html">
        <img src="../../assets/admin/layout/img/logo-big.png" alt=""/>
    </a>
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="content">


    <!-- BEGIN REGISTRATION FORM -->
    <form class="register-form" action="index.html" method="post" style="display: block">
        <h3>Sign Up</h3>
        <p>
            Enter your personal details below:
        </p>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Full Name</label>
            <div class="input-icon">
                <i class="fa fa-font"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Full Name" name="fullname"/>
            </div>
        </div>

        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Email" name="email"/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Address</label>
            <div class="input-icon">
                <i class="fa fa-check"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Address" name="address"/>
            </div>
        </div>

        <p>
            Enter your account details below:
        </p>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Username</label>
            <div class="input-icon">
                <i class="fa fa-user"></i>
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username"/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Password</label>
            <div class="input-icon">
                <i class="fa fa-lock"></i>
                <input class="form-control placeholder-no-fix" type="password" autocomplete="off" id="register_password" placeholder="Password" name="password"/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Re-type Your Password</label>
            <div class="controls">
                <div class="input-icon">
                    <i class="fa fa-check"></i>
                    <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Re-type Your Password" name="rpassword"/>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button id="register-back-btn" type="button" class="btn">
                <i class="m-icon-swapleft"></i> Back </button>
            <button type="submit" id="register-submit-btn" class="btn green pull-right">
                Sign Up <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
    <!-- END REGISTRATION FORM -->
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
    2014 &copy; Metronic. Admin Dashboard Template.
</div>
<!-- END COPYRIGHT -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/respond.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/excanvas.min.js') ?>
<![endif]-->
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-1.11.0.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-migrate-1.2.1.min.js') ?>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/bootstrap/js/bootstrap.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery.blockui.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery.cokie.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/uniform/jquery.uniform.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js') ?>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-validation/js/jquery.validate.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/select2/select2.min.js') ?>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<?php echo $this->headScript()->prependFile('/admin/assets/global/scripts/metronic.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/admin/layout/scripts/layout.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/admin/layout/scripts/quick-sidebar.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/admin/pages/scripts/login.js') ?>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function() {
        Metronic.init(); // init metronic core components
        Layout.init(); // init current layout
        QuickSidebar.init() // init quick sidebar
        Login.init();
    });
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>