<div class="col-md-9 col-sm-7">
    <div class="product-page">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="product-main-image">
                    <img src="<?php echo $this->baseUrl() . '/upload/' . $this->product_detail['img1']?>" alt="Cool green dress with red bell" class="img-responsive" data-BigImgsrc="<?php echo $this->baseUrl() . '/upload/' . $this->product_detail['img1']?>">
                </div>
                <div class="product-other-images">
                    <a href="<?php echo $this->baseUrl(). '/upload/' . $this->product_detail['img2']?>" class="fancybox-button" rel="photos-lib">
                        <img alt="Berry Lace Dress" src="<?php echo $this->baseUrl() . '/upload/' . $this->product_detail['img2']?>">
                    </a>
                    <a href="<?php echo $this->baseUrl() . '/upload/' . $this->product_detail['img3']?>" class="fancybox-button" rel="photos-lib">
                        <img alt="Berry Lace Dress" src="<?php echo $this->baseUrl() . '/upload/' . $this->product_detail['img3']?>">
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <h1><?=$this->product_detail['product_name']?></h1>
                <div class="price-availability-block clearfix">
                    <div class="price">
                        <strong><span>$<?=$this->product_detail['price']?></span></strong>

                    </div>
                </div>
                <div class="description">
                    <p><?=$this->product_detail['title']?></p>
                </div>
                <div class="product-page-options">
                    <div class="pull-left">
                        <label class="control-label">Size:</label>
                        <select class="form-control input-sm">
                            <?php foreach ($this->product_extend as $size): ?>
                                <option value="<?=$size['size']?>">
                                    <?=$size['size']?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="pull-left">
                        <label class="control-label">Color:</label>
                        <select class="form-control input-sm">
                           <?php foreach ($this->product_extend as $size): ?>
                                <option value="<?=$size['color_name']?>">
                                    <?=$size['color_name']?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="product-page-cart">
                    <div class="product-quantity">
                        <input id="product-quantity" type="text" value="1" readonly class="form-control input-sm">
                    </div>
                    <button class="btn btn-primary" type="submit">Add to cart</button>
                </div>
                <div class="review">
                    <a href="#"><?=$this->product_detail['total_view']?> views</a>
                </div>
            </div>

            <div class="product-page-content">
                <ul id="myTab" class="nav nav-tabs">
                    <li class="active"><a href="#Description" data-toggle="tab">Description</a></li>
                    <li><a href="#Information" data-toggle="tab">Information</a></li>
                </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane active in fade" id="Description">
                        <p>
                            <?=$this->product_detail['description']?>
                        </p>
                    </div>
                    <div class="tab-pane fade" id="Information">
                        <table class="datasheet">
                            <tr>
                                <th colspan="2">Additional features</th>
                            </tr>
                            <?php foreach ($this->product_info as $info): ?>
                            <tr>
                                <td class="datasheet-features-type"><?=$info['title']?></td>
                                <td><?=$info['description']?></td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>
            </div>

            <div class="sticker sticker-sale"></div>
        </div>
    </div>
</div>