<?php echo $this->doctype() ?>
<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 3.1.2
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8"/>
    <title>Metronic | Admin Dashboard Template</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/font-awesome/css/font-awesome.min.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/simple-line-icons/simple-line-icons.min.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/bootstrap/css/bootstrap.min.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/uniform/css/uniform.default.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css') ?>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/gritter/css/jquery.gritter.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/fullcalendar/fullcalendar/fullcalendar.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/plugins/jqvmap/jqvmap/jqvmap.css') ?>
    <!-- END PAGE LEVEL PLUGIN STYLES -->
    <!-- BEGIN PAGE STYLES -->
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/admin/pages/css/tasks.css') ?>
    <!-- END PAGE STYLES -->
    <!-- BEGIN THEME STYLES -->
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/css/components.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/global/css/plugins.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/admin/layout/css/layout.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/admin/layout/css/themes/default.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/admin/assets/admin/layout/css/custom.css') ?>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico"/>
    <style>
        .fileinput-button input {
            position: absolute;
            top: 0;
            right: 0;
            width: 100px;
            height: 30px;
            margin: 0;
            opacity: 0;
            -ms-filter: 'alpha(opacity=0)';
            font-size: 200px;
            direction: ltr;
            cursor: pointer;
        }
    </style>
</head>
<body class="page-header-fixed page-quick-sidebar-over-content">
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner">
        <!-- BEGIN LOGO -->
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                <li class="dropdown dropdown-quick-sidebar-toggler">
                    <a href="/admin/auth/logout" class="dropdown-toggle">
                        <i class="icon-logout"></i>
                    </a>
                </li>
                <!-- END QUICK SIDEBAR TOGGLER -->
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<div class="clearfix">
</div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
            <ul class="page-sidebar-menu" data-auto-scroll="true" data-slide-speed="200">
                <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
                <li class="sidebar-toggler-wrapper">
                    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                    <div class="sidebar-toggler">
                    </div>
                    <!-- END SIDEBAR TOGGLER BUTTON -->
                </li>
                <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
                <li class="start active open">
                    <a href="/admin/account">
                        <i class="icon-home"></i>
                        <span class="title">Account</span>
                        <span class="selected"></span>
                    </a>
                </li>
                <li class="start">
                    <a href="/admin/product">
                        <span class="title">Products</span>
                        <span class="selected"></span>
                    </a>
                </li>
                <li class="start">
                    <a href="/admin/category">
                        <span class="title">Categories</span>
                        <span class="selected"></span>
                    </a>
                </li>
                <li>
                    <a href="/admin/product-extend">
                        <i class="icon-bar-chart"></i>
                        Product Extend</a>
                </li>
                <li>
                    <a href="/admin/product-color">
                        <i class="icon-bulb"></i>
                        Product Color</a>
                </li>
            </ul>
            <!-- END SIDEBAR MENU -->
        </div>
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

            <!-- BEGIN PAGE HEADER-->
            <div class="row">
                <div class="col-md-12">
                    <ul class="page-breadcrumb breadcrumb">
                        <li>
                            <i class="fa fa-home"></i>
                            <a href="/admin/account">Account</a>
                            <i class="fa fa-angle-right"></i>
                        </li>
                        <li>
                            <a href="#">Dashboard</a>
                        </li>
                        <li class="pull-right">
                            <div id="dashboard-report-range" class="dashboard-date-range tooltips" data-placement="top" data-original-title="Change dashboard date range">
                                <i class="icon-calendar"></i>
                                <span></span>
                                <i class="fa fa-angle-down"></i>
                            </div>
                        </li>
                    </ul>
                    <!-- END PAGE TITLE & BREADCRUMB-->
                </div>
            </div>
            <!-- END PAGE HEADER-->
            <div class="clearfix">
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
                    <?php if($flashMessenger->hasMessages('error')): ?>
                        <div class="note note-danger">
                            <?php foreach ($flashMessenger->getMessages('error') as $msg): ?>
                                <?php echo '<p>' .  $msg . '</p>' ?>
                            <?php endforeach; ?>
                        </div>
                    <?php elseif ($flashMessenger->hasMessages('success')): ?>
                        <div class="note note-success">
                            <?php foreach ($flashMessenger->getMessages('success') as $msg): ?>
                                <?php echo '<p>' .  $msg . '</p>' ?>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </div>
    <!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner">
        2014 &copy; Metronic by keenthemes.
    </div>
    <div class="page-footer-tools">
		<span class="go-top">
		<i class="fa fa-angle-up"></i>
		</span>
    </div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/respond.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/excanvas.min.js') ?>
<![endif]-->
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-1.11.0.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-migrate-1.2.1.min.js') ?>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/bootstrap/js/bootstrap.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery.blockui.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery.cokie.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/uniform/jquery.uniform.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js') ?>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/fullcalendar/fullcalendar/fullcalendar.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/jquery.sparkline.min.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/global/plugins/gritter/js/jquery.gritter.js') ?>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<?php echo $this->headScript()->prependFile('/admin/assets/global/scripts/metronic.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/admin/layout/scripts/layout.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/admin/layout/scripts/quick-sidebar.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/admin/pages/scripts/index.js') ?>
<?php echo $this->headScript()->prependFile('/admin/assets/admin/pages/scripts/tasks.js') ?>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function() {
        //Metronic.init(); // init metronic core componets
        Layout.init(); // init layout
        QuickSidebar.init() // init quick sidebar
        // Index.init();
        // Index.initDashboardDaterange();
        // Index.initJQVMAP(); // init index page's custom scripts
        // Index.initCalendar(); // init index page's custom scripts
        // Index.initCharts(); // init index page's custom scripts
        // Index.initChat();
        // Index.initMiniCharts();
        // Index.initIntro();
        // Tasks.initDashboardWidget();
    });

    setTimeout(function () {
        $('.note').fadeOut('slow')
    }, 5000)

    $('#add-item-inventory').on('click', function () {
        let item = $('#add-inventory-item').first().html();
        $('#add-inventory-item').append(item)
    });

    function deleteItem(_this) {
        let item = $('#add-inventory-item tr').length;
        if (item >  1) {
            _this.parents('tr').remove();
        }
    }
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
