<div class="col-md-12">
    <div class="portlet box purple ">
        <div class="portlet-body form">
            <form class="form-horizontal" role="form" method="post" action="/admin/product-extend/create">
                <div class="form-body">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Size</label>
                        <div class="col-md-5">
                            <input type="text" name="size" required class="form-control input-lg" placeholder="Category Name">
                        </div>
                    </div>
                </div>
                <div class="form-actions right">
                    <a href="/admin/product-extend" class="btn default">Cancel</a>
                    <button type="submit" class="btn green">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>