<div class="col-md-12">
	<!-- BEGIN SAMPLE TABLE PORTLET-->
	<div class="row">
		<form class="form-horizontal" role="form" method="post" action="/admin/product-extend/create">
			<div class="col-md-9">
				<div class="form-group">
					<label class="col-md-3 control-label">Size</label>
					<div class="col-md-5">
						<input type="text" name="size" required class="form-control" placeholder="XXL">
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<button type="submit" class="btn green">Submit</button>
			</div>
		</form>
	</div>

	<div class="portlet box red">
		<div class="portlet-body">
			<div class="table-scrollable">
				<table class="table table-hover">
					<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Size
						</th>
						<th>
							Created
						</th>
						<th>
							Modified
						</th>
						<th>
							Action
						</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach ($this->product_extends as $product): ?>
					<tr>
						<form action="/admin/product-extend/update" method="post">
						<td>
							<?= $product['id'] ?>
							<input type="hidden" name="id" value="<?=$product['id']?>">
						</td>
						<td>
							<input type="text" name="size" class="form-control" value="<?=$product['size']?>">
						</td>
						<td>
							<?= $product['created_at'] ?>
						</td>
						<td>
							<?= $product['updated_at'] ?>
						</td>
						<td>
							<a href="/admin/product-extend/delete?id=<?=$product['id']?>"
							   class="btn btn-sm red filter-cancel" onclick="return confirm('Are you sure?')">
								<i class="fa fa-times"></i>
								Delete
							</a>
							<button type="submit"
							   class="btn btn-sm green filter-cancel">
								<i class="fa fa-check-circle"></i>
								Update
							</button>
						</td>
						</form>
					</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- END SAMPLE TABLE PORTLET-->
</div>